-- MySQL Script generated by MySQL Workbench
-- 11/18/16 15:18:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
CREATE database mydb;
USE mydb;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE usuario (
  idusuario INT NOT NULL,
  nombreUsuario VARCHAR(45) NULL,
  pass VARCHAR(45) NULL,
  nombre VARCHAR(45) NULL,
  apellido VARCHAR(45) NULL,
  fechaNac VARCHAR(45) NULL,
  sexo VARCHAR(45) NULL,
  dui VARCHAR(45) NULL,
  direccion VARCHAR(45) NULL,
  telefono VARCHAR(45) NULL,
  movil VARCHAR(45) NULL,
  correoElectronico VARCHAR(45) NULL,
  especialidad VARCHAR(45) NULL,
  numeroJVPM VARCHAR(45) NULL,
  tipoRol VARCHAR(45) NULL,
  PRIMARY KEY (idusuario));



-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE paciente (
  idpaciente INT NOT NULL,
  nombrePaciente VARCHAR(45) NULL,
  apellidoPaciente VARCHAR(45) NULL,
  direccionPaciente VARCHAR(45) NULL,
  telPaciente VARCHAR(45) NULL,
  movilPaciente VARCHAR(45) NULL,
  infoEmergencia VARCHAR(45) NULL,
  PRIMARY KEY (idpaciente));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recetaMedica`
-- -----------------------------------------------------
CREATE TABLE recetaMedica (
  idrecetaMedica INT NOT NULL,
  nombreReceta VARCHAR(45) NULL,
  PRIMARY KEY (idrecetaMedica));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE citas (
  idcitas INT NOT NULL,
  fecha VARCHAR(45) NULL,
  estadoCita VARCHAR(45) NULL,
  recetaMedica_idrecetaMedica INT NOT NULL,
  paciente_idpaciente INT NOT NULL,
  usuario_idusuario INT NOT NULL,
  PRIMARY KEY (idcitas, recetaMedica_idrecetaMedica, paciente_idpaciente, usuario_idusuario),
  INDEX fk_citas_recetaMedica_idx (recetaMedica_idrecetaMedica ASC),
  INDEX fk_citas_paciente1_idx (paciente_idpaciente ASC),
  INDEX fk_citas_usuario1_idx (usuario_idusuario ASC),
  CONSTRAINT fk_citas_recetaMedica
    FOREIGN KEY (recetaMedica_idrecetaMedica)
    REFERENCES recetaMedica (idrecetaMedica)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_citas_paciente1
    FOREIGN KEY (paciente_idpaciente)
    REFERENCES paciente (idpaciente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_citas_usuario1
    FOREIGN KEY (usuario_idusuario)
    REFERENCES usuario (idusuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expedienteMedico`
-- -----------------------------------------------------
CREATE TABLE expedienteMedico (
  idexpedienteMedico INT NOT NULL,
  presionArterial VARCHAR(45) NULL,
  temperatura VARCHAR(45) NULL,
  observaciones VARCHAR(45) NULL,
  paciente_idpaciente INT NOT NULL,
  PRIMARY KEY (idexpedienteMedico, paciente_idpaciente),
  INDEX fk_expedienteMedico_paciente1_idx (paciente_idpaciente ASC),
  CONSTRAINT fk_expedienteMedico_paciente1
    FOREIGN KEY (paciente_idpaciente)
    REFERENCES paciente (idpaciente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
--ENGINE = InnoDB;

